### ISSUE TITLE
Layer expects 60 weight(s). Received 62 saved weight(s)

### ISSUE THREAD

**Issue by lkathke** [braindotai/Super-Resolution-for-Real-Time-Image-Enhancement#4]
Hello,

I am trying to run this project, but I can't. I am currently getting this, when I run inference.py:

Traceback (most recent call last):
  File "/home/lasse/Real-Time-Super-Resolution/inference.py", line 6, in <module>
    generator.load_weights('weights/GeneratorVG4(1520).h5')
  File "/home/lasse/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/lasse/.local/lib/python3.10/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 369, in load_weights_from_hdf5_group
    raise ValueError(
ValueError: Weight count mismatch for layer #2 (named rrd_block in the current model, rrd_block in the save file). Layer expects 60 weight(s). Received 62 saved weight(s)

**Comment by sam3012** [comment]
(Same issue 🙌) `Edited` Use `python=3.7` while creating `conda env` and then `pip install -r requirements.txt`

**Comment by lkathke** [comment]
Thanks for the hint! Now its working 🙌🥳
